### ISSUE TITLE
D3D12RenderSystem::Render_MeshNodes checks execute indirect multiple times

### ISSUE THREAD

**Issue by florianschut** [TeamWisp/WispRenderer#115]
Some nested if statement are unnecesarry and wastefull. May be more frequent in d3d12_renderer.cpp

if constexpr (d3d12::settings::use_exec_indirect)
{...}
else
{
if constexpr (!d3d12::settings::use_exec_indirect)
{...}
}

**Comment by Nielsbishere** [comment]
More of a code change though, if it's an if with constexpr it will be optimized out anyways.

**Comment by VZout** [comment]
Removed execute indirect.
