### ISSUE TITLE
Use C++'s "final" keyword to clarify design choice.

### ISSUE THREAD

**Issue by sainsay** [TeamWisp/WispRenderer#117]
**Is your request related to a problem? Please describe.**
D3D12RenderSystem class can currently be inherited from but marks all virtual functions as final giving no use to the child class. maintaining D3D12RenderSystem when the RenderSystem class changes can introduce mistakes as it is not clear that D3D12RenderSystem is not supposed to be inherited from in current design philosophy.

**Describe the solution you'd like**
D3D12RenderSystem class marked with the final specifier and remove in necessary final specifiers from functions. this makes all future additions to RenderSystem when virtual to be final in the D3D12RenderSystem. 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by VZout** [comment]
Fixed in #323
