### ISSUE TITLE
Sun Temple DDS mipmapping bug.

### ISSUE THREAD

**Issue by LaisoEmilio** [TeamWisp/WispRenderer#177]
**Describe the bug**
Textures from sun temple, when loaded, return a number of mip level that is of 12, but the dds texture only has proper mip levels created up to a certain level < than 12. After that, black and yellow striped textures are contained in the mip levels, which results in those textures being displayed on screen when that mip level is reached.

**To Reproduce**
* Load a dds texture from Sun temple as one of the scene materials. (Just the albedo works fine)
* Move the camera further away from the scene and see the striped texture appear on the models
* Another way is also using Nvidia Nsight Graphics and inspecting the resource mip levels.

**Expected behaviour**
We expect those textures to have proper mip levels, but we have to properly test with different textures as this is not a bug in the mipmapping implementation.

**Comment by VZout** [comment]
Fixed
