### ISSUE TITLE
Resizing window leaks memory

### ISSUE THREAD

**Issue by LaisoEmilio** [TeamWisp/WispRenderer#186]
**Describe the bug**
Resizing the engine window causes memory to leak. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the project in Visual Studio
2. Click on the corner of the window and keep resizing it
3. Keep an eye on the Process Memory graph in the Diagnostic Tool
4. Notice how the memory goes up, but never gets freed.

**Expected behaviour**
If memory goes up because something needs to be allocated, the expected behaviour is that then, after the resizing is done, it should go back down to the level it was before.

**Comment by DBouma** [comment]
As of 3/25/2019 in my feature DoF branch , the resizing eventually causes a crash at deferred composition at creating the UAV. (CreateUAVfromRTV)

**Comment by VZout** [comment]
Much improvement but still seems to leak.

**Comment by Nielsbishere** [comment]
https://github.com/TeamWisp/WispRenderer/pull/396
