### ISSUE TITLE
More texture file formats

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/WispRenderer#196]
**Is your feature request related to a problem? Please describe.**
We only support a few file formats. If we want people to use the plug-in, we should support more of the most common file formats such as JPG etc.

**Describe the solution you'd like**
I'd like to see support for more image formats.

**Describe alternatives you've considered**
I considered forcing people to use png files everywhere, but that doesn't seem like a good solution.

**Additional context**
Not applicable.

**Comment by VZout** [comment]
We support jpeg, tga and bmp now. If we need more types I'll reopen the issue.
