### ISSUE TITLE
Change the name of the repository

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/WispRenderer#203]
**Is your feature request related to a problem? Please describe.**
There's no problem whatsoever, however, I'd like to link people to a repository that has a sensible name. This is currently not the case.

**Describe the solution you'd like**
I'd like to see the name of this repository changed to something that matches the project a lot better.

**Describe alternatives you've considered**
Not applicable.

**Additional context**
I'd like to start posting to Reddit and other forums as well, and it doesn't make sense to link to the repository right now.

**Comment by VZout** [comment]
Good point. Will do after week 8 to prevent git setups being broken.

**Comment by VZout** [comment]
Done!
