### ISSUE TITLE
More visually pleasing README.MD

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/WispRenderer#204]
**Is your feature request related to a problem? Please describe.**
The current readme is boring and doesn't let people know what our renderer is capable of.

**Describe the solution you'd like**
I'd like to see screenshots and a short description of the project. As well as some kind of installation manual.

**Describe alternatives you've considered**
Linking to our Wiki is not convenient for users.

**Additional context**
I'd like to post links to the repository on forums (relevant issue: #203), so this change would be very much appreciated. I'd do it myself if I had the time for it...

**Comment by VZout** [comment]
Merged with master. Closing for now.
