### ISSUE TITLE
~D3D12TexturePool() unloads unstaged textures 

### ISSUE THREAD

**Issue by sainsay** [TeamWisp/WispRenderer#213]
**Describe the bug**
During deconstruction of D3D12TexturePool. Unstaged textures are unloaded. Code crashes on nullptr.

**To Reproduce**
Deconstruct D3D12TexturePool while having unstaged textures.

**Expected behaviour**
unstaged textures do not have to be unloaded at all.

**Additional context**
file: d3d12_resource_pool_texture.cpp: L98 - L101

**Comment by Nielsbishere** [comment]
Hasn't occurred in a while, might have been fixed since refactoring the texture pool

**Comment by VZout** [comment]
I believe this is fixed as well. Closing for now.
