### ISSUE TITLE
UpdateTransform remove used_quaternion flag

### ISSUE THREAD

**Issue by sainsay** [TeamWisp/WispRenderer#237]
**Is your request related to a problem? Please describe.**
Current solution is hacky and error prone.
node.cpp

**Describe the solution you'd like**
remove the need for a boolean by converting EulerRotation to Quaternion values when setting rotation in node.cpp instead of doing the conversion during UpdateTransform()

**Comment by Nielsbishere** [comment]
Related to https://github.com/TeamWisp/Procedural-Ray-Tracing/issues/121

**Comment by VZout** [comment]
Closing since its mostly duplicate from #121.
