### ISSUE TITLE
Raytracing normals issue

### ISSUE THREAD

**Issue by Nielsbishere** [TeamWisp/WispRenderer#242]
**Describe the bug**
Normals don't point away from the camera (since normals pointing away will always be occluded or culled), resolve normals that do, to prevent artifacts.

**To Reproduce**
Go to viknell, look at shadows (and reflections) on the opposite side of the planes.

**Expected behaviour**
The shadows shouldn't be there and light should reflect, but it looks like it passes through (since it uses the plane's normal that's oriented the wrong way). 

**Screenshots**
![X-ray vision](https://imgur.com/F5zGPcG.jpg)
^ Occurs if you use the normal with epsilon

**Desktop (please complete the following information):**
Tower

**Additional context**
N.A.

**Comment by Nielsbishere** [comment]
https://github.com/TeamWisp/Procedural-Ray-Tracing/pull/243

**Comment by Nielsbishere** [comment]
Seems like it happens again in master.

**Comment by VZout** [comment]
I believe I fixed this in the normal refactor.
