### ISSUE TITLE
Terrible performance on GTX 960M

### ISSUE THREAD

**Issue by Nielsbishere** [TeamWisp/WispRenderer#246]
**Describe the bug**
Runs at 15 fps on full screen, otherwise 24 fps (on deferred).

**To Reproduce**
Try on a low-end desktop/laptop.

**Expected behaviour**
Run at a higher fps.

**Screenshots**
N.A.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: master (37909791dc3693b8b48bc4276f10ad4a403b8803)
 - Hardware: GPU: 960M, RAM: 16 GiB, CPU: N.A.

**Additional context**
100% GPU usage, so GPU bound. Downloading NSight to look into it further.

**Comment by Nielsbishere** [comment]
Looked into it more, it's because my VRAM ran out and it's using shared memory instead.

**Comment by Nielsbishere** [comment]
https://github.com/TeamWisp/Procedural-Ray-Tracing/issues/248

**Comment by VZout** [comment]
Duplicate with #248, Closing
