### ISSUE TITLE
Raytracing reflection rays return invalid data.

### ISSUE THREAD

**Issue by DBouma** [TeamWisp/WispRenderer#250]
With hybrid / full / path tracing, the reflection rays return garbage data. Seems to be related to sampling from the skysphere.
Clamping the output between 0 and 2 seems to greatly reduce the artefacts but this is only a temporary hackfix.

Steps to reproduce the behaviour:
1. Start up the project on debug or release
2. Switch to hybrid/full raytracing/path tracing
3. Notice extremely bright or negative pixel values in form of noise.

**Comment by VZout** [comment]
Fixed
