### ISSUE TITLE
Passing nullopt as RenderTaskDesc.m_properties crashes

### ISSUE THREAD

**Issue by Nielsbishere** [TeamWisp/WispRenderer#252]
**Describe the bug**
Passing nullopt as RenderTaskDesc.m_properties crashes

**To Reproduce**
Replace d3d12_cubemap_convolution.hpp's m_properties with std::nullopt.

**Expected behaviour**
It shouldn't crash, because it's unused.

**Desktop (please complete the following information):**
N.A.

**Additional context**
N.A.

**Comment by VZout** [comment]
Fixed it!
