### ISSUE TITLE
Use uints when needed

### ISSUE THREAD

**Issue by Nielsbishere** [TeamWisp/WispRenderer#288]
**Is your design request related to a problem? Please describe.**
Floats are used instead of integers for texture handles and things like offsets. This is not only bad practice but also results in problems when we reach >8M vertices or indices. 

**Describe the solution you'd like**
Whenever using integer data, use a uint; don't use a float just cause it's easy.

**Describe alternatives you've considered**
**Additional context**
N.A.

**Comment by VZout** [comment]
Fixed it will close when merged.
