### ISSUE TITLE
Wisp crashes if no imgui.ini file is present 

### ISSUE THREAD

**Issue by LaisoEmilio** [TeamWisp/WispRenderer#356]
The engine crashes on startup if no imgui.ini file is present in the root folder.

To reproduce:
- Switch to master branch
- Delete imgui.ini file from root folder
- Watch it happen!

**Comment by VZout** [comment]
Fixed in

**Comment by VZout** [comment]
https://github.com/TeamWisp/WispRenderer/pull/357
