### ISSUE TITLE
Scene changer always loads Sponza

### ISSUE THREAD

**Issue by 161563** [TeamWisp/WispRenderer#381]
**Describe the bug**
The scene loader always loads the Sponza scene, no matter which option is selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the scene changer
2. Select any scene
3. Hit Load
4. A sponza appears.

**Expected behaviour**
The specified scene should be loaded, not Sponza.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 1809
 - Hardware CPU: i7-6700K, GPU: RTX 2080 TI, RAM: 64GB

**Comment by VZout** [comment]
Fixed
