### ISSUE TITLE
Use a bitset instead of a vector for versioning in the SceneGraph Node's

### ISSUE THREAD

**Issue by Nielsbishere** [TeamWisp/WispRenderer#56]
node.hpp specifies `std::bitset<3>` (`std::vector<3>` before, but changed for performance reasons). This means that when a different type of buffering is used (double or quadruple) the required_update field is accessed the wrong way.

**Comment by Nielsbishere** [comment]
Low priority, since double buffering would still have less than 3 buffers and quadruple buffering won't be used. Also, probably a lot of work, since a lot of values are hardcoded to 3 instead of d3d12::settings's num back buffers.

**Comment by VZout** [comment]
This is already implemented. Not sure what PR though.
