### ISSUE TITLE
Execute Indirect: Only rendering third frame

### ISSUE THREAD

**Issue by 161563** [TeamWisp/WispRenderer#59]
Execute indirect will only render every third frame. Likely to be related to versioning.

**Comment by VZout** [comment]
Tried this, Seems to work fine. Maybe only when the GPU can't finish execution fast enough.

**Comment by VZout** [comment]
Looking at the code it would make sense if execute indirect works inconsistently on slower hardware. Updating only the 3e frames seems weird to me though.

**Comment by 161563** [comment]
This has changed with the introduction of the dxr fallback layer. In the third frame, it now crashes when Transition is called on the render target.

**Comment by 161563** [comment]
Error is: D3D12 WARNING: ID3D12CommandQueue::ExecuteCommandLists: Execution of Command List 0x00000255402C19C0:'Unnamed Resource (line: 32 file: D:\School\IGAD Y3\Procedural-Ray-Tracing\src\d3d12\d3d12_command_list.cpp', contains a shader op (Draw/Dispatch/ExecuteIndirect) recorded while using Shader Patch Mode NONE, or contains an ExecuteIndirect that changes VB/IB/Root bindings. Hence, all further GPU-based validation may undervalidate or produce true GBV errors with imprecise tracked state (labelled with 'Possibly imprecise') for resources in the COMMON state or Promoted-from-COMMON state at the time of execute. [ EXECUTION WARNING #1044: GPU_BASED_VALIDATION_RESOURCE_STATE_IMPRECISE]
D3D12: Removing Device.

**Comment by VZout** [comment]
Removed execute indirect.
