### ISSUE TITLE
Inconsistent placement of "&" and "*"

### ISSUE THREAD

**Issue by tntmeijs** [TeamWisp/WispRenderer#71]
The codebase seems to switch styles every now and then. Intellisense function definition generation settings seem to be inconsistent and need to be updated to keep the codebase clean and coherent.

Some examples:
- `int foo(const MyObject& bar) {}`
- `int foo(const MyObject & bar) {}`

The same thing applies to functions that contain pointers. The asterisk is not placed in the same location every single time.

**Comment by tntmeijs** [comment]
It seems to mainly be caused by auto-generated functions when using the Intellisense functionality to create function implementations.

I will get back to you with the specific places in code.

**Comment by VZout** [comment]
Closing for now. Will reopen if we run into examples of this.
